### PR TITLE
Continued the inital project setup by modifying the following files ...

### PR DESCRIPTION
**Pull request by bngwanforbi**
Continued the initial project setup by modifying the following files- fresh_start/templates/fresh_start/base.html, fresh_start/templates/fresh_start/home.html, fresh_start/urls.py, fresh_start/views.py, mysite/settings.py, and mysite/urls.py.

- Set up some URL routes so that we can start directing people to pages that we'd like them to see.
- Created a new file called **urls.py**. This module is similar to the urls module in the _mysite_ directory. We can see that it imported path. It also has a list of url patterns that are using those paths. The **urls.py** module also imports the **views.py** module. The paths being used by the url patterns are _fresh_start-home_ and _fresh_start-about_.
- Created new functions called **home** and **about** to handle traffic from the home page of our website. These functions take in a request argument to get our functions to work. Within these functions, we're simply returning what we want the user to see when they're sent to the routes.

- Used templates to return more complex HTML code. Created a templates directory within our fresh_start directory. We use templates so we don't have to repeat HTML code for every single one of our HTML pages. 
- Created the _home_ and _about_ templates.
- Updated our entire website to use bootstrap via a static **main.css** file, taking advantage of template inheritance to make our pages look nicer.

- Lastly, created three admin users for the fresh_start project: @Suenodivino, @Intheloop83, and @bngwanforbi, and gave them all staff status and superuser status.

### CODE REVIEW

**Review by Suenodivino — APPROVED** [review]
@bngwanforbi Looks great!

**Comment by Intheloop83** [comment]
Good stuff! Great start!

**Review by Intheloop83 — COMMENTED** [review]
Nice. Good stuff!

**Review by Intheloop83 — COMMENTED** [review]
Good start!

**Review by Intheloop83 — APPROVED** [review]

**Pull request merged**
